### ISSUE TITLE
ssl_verify on Ubuntu 16.04

### ISSUE THREAD

**Issue by thehilll** [voxpupuli/pypuppetdb#133] opened 2018-01-26 20:05 UTC
Hello,

On Ubuntu 16.04 hen following your instructions to trust our puppet CA given here:

https://pypuppetdb.readthedocs.io/en/v0.1.0/quickstart.html#ssl

and setting `ssl_verify=True` I get no data and an error:

`(Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))`

if I omit `ssl_verify` I get the query result and an `InsecureRequestWarning`.  In both cases I have run `update-ca-certificates` and would expect successful verification.  When I run the query with `curl` and don't specify a CA cert I get a successful connection.

Looking at `api.py` it looks like `ssl_verify` is passed to the requests `verify` argument as is:

```
r = self._session.get(url, params=payload,
                                      verify=self.ssl_verify,
                                      cert=(self.ssl_cert, self.ssl_key),
                                      timeout=self.timeout,
                                      auth=auth)
```

and then on the requests docs it looks like verify should be the path to the trusted certificate file or directory.  When I set `ssl_verify='/etc/ssl/certs'` I get the correct query results with no warning.

I'm not sure if this true on other platforms or if it is new, but it seems like you can't trust a custom cert w/o specifying the path currently.

Thanks.

**Comment by mterzo** [comment] 2018-01-26 20:21
It's more about the version of python and some of the SSL library packages that came with 2.7.
ssl_verify is either False, or a path to the SSL key chain.

PuppetDB runs on 2 ports 8080 on localhost and 8081 on all interfaces.  If you are on the local machine you use the 8080 URL and you do not need any sort of SSL Key.  If you are remove you will need to use 8081 for SSL and you will have to provide the puppetdb SSL key with curl.

Sounds like when you are using pypuppet you are using 8081 and your curl is using 8080.

Those docs on readthedocs.org are old, I didn't even knew the existed.  I guess I need to figure out how to update those docs.  There are changes to python and how it manages SSL key trusts.

Your best bet is to not put the puppetdb key in your SSL keychain and just keep it somewhere with your code so that you can reference it with ssl_verify='/path to ssl'  unless you are doing everything local.

**Comment by thehilll** [comment] 2018-01-26 20:31
These are all remote (curl and pypuppetdb), and each of them explicitly specified port 8081.

But you are right, this is really just a documentation issue...using ssl_verify='/path to ssl' is really easier than importing the puppet CA certificate into the host trusted certs.

Thanks.

**Comment by b4ldr** [comment] 2020-02-19 20:00
this is similar to #143

**Comment by gdubicki** [comment] 2021-02-27 13:11
I would say that this is a duplicate of #143, so I will close this. But feel free to reopen if you disagree. :)

**Closed by gdubicki** 2021-02-27 13:11 UTC
